// Generated by CoffeeScript 1.4.0
(function() {
  var code, codes, file, files, fs, path, targetFile, threeMathDir, _i, _len;

  fs = require("fs");

  path = require("path");

  threeMathDir = "./Threejs/src/math/";

  targetFile = "./common/threeMath.js";

  files = fs.readdirSync(threeMathDir);

  codes = [];

  for (_i = 0, _len = files.length; _i < _len; _i++) {
    file = files[_i];
    codes.push(fs.readFileSync(path.join(threeMathDir, file)).toString());
  }

  code = "THREE = {}\nexports.THREE = THREE;\n" + (codes.join(';\n'));

  fs.writeFileSync(targetFile, code);

}).call(this);
