// Generated by CoffeeScript 1.4.0
(function() {
  var code, fs, path, targetFile, three, threeCode;

  fs = require("fs");

  path = require("path");

  three = "./Threejs/build/three.js";

  targetFile = "./common/three-node.js";

  threeCode = fs.readFileSync(three).toString();

  code = "self = global\nwindow = global\n" + threeCode + "\nexports.THREE = THREE\nexports.Three = THREE";

  fs.writeFileSync(targetFile, code);

}).call(this);
