// Generated by CoffeeScript 1.4.0
(function() {
  var EventEmitter,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  EventEmitter = (require("events")).EventEmitter;

  (function(_super) {

    __extends(_Class, _super);

    function _Class() {
      this.world = new World();
    }

    _Class.prototype.init = function() {};

    _Class.prototype.update = function(info) {};

    return _Class;

  })(EventEmitter);

}).call(this);
